clean: true
author: ApolloZhu
author_url: https://apollozhu.github.io
github_url: https://github.com/ApolloZhu/BilibiliKit
github-file-prefix: https://github.com/ApolloZhu/BilibiliKit/blob/master
xcodebuild_arguments [-target, BilibiliKit]
module: BilibiliKit
root-url: https://apollozhu.github.io/BilibiliKit/
dash_url: https://apollozhu.github.io/BilibiliKit/docsets/BilibiliKit
