clean: true
author: ApolloZhu
author_url: https://apollozhu.github.io
github_url: https://github.com/ApolloZhu/BilibiliKit
github_file_prefix: https://github.com/ApolloZhu/BilibiliKit/blob/master
root_url: https://apollozhu.github.io/BilibiliKit/
dash_url: https://apollozhu.github.io/BilibiliKit/docsets/BilibiliKit
