clean: true
author: ApolloZhu
author_url: https://apollozhu.github.io
github_url: https://github.com/ApolloZhu/BilibiliKit
xcodebuild_arguments: [-target, BilibiliKit]
module: BilibiliKit
dash_url: https://apollozhu.github.io/BilibiliKit/docsets/BilibiliKit
