language: generic
matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2

before_script:
  - eval "$(curl -sL https://raw.githubusercontent.com/ApolloZhu/script/master/swift/install/5)"
script:
  - eval "$(curl -sL https://raw.githubusercontent.com/ApolloZhu/script/master/swift/ci)"

before_deploy:
  - sudo gem install jazzy
  - swift package generate-xcodeproj
  - jazzy --root-url https://apollozhu.github.io/BilibiliKit/ --github-file-prefix https://github.com/ApolloZhu/BilibiliKit/blob/master
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = osx
