language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
#    - os: linux
#      dist: trusty
#    - os: linux
#      dist: xenial

before_script:
  - eval "$(curl -sL https://raw.githubusercontent.com/ApolloZhu/script/master/swift/install/5)"
script:
  - eval "$(curl -sL https://raw.githubusercontent.com/ApolloZhu/script/master/swift/ci)"

before_deploy:
  - sudo gem install jazzy
  - jazzy spm
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = osx
