name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Build Release
      run: swift build -v -c release
    - name: Run Tests
      run: swift test -v
      env:
        BILI_USER: ${{ secrets.BILI_USER }}
        BILI_PASS: ${{ secrets.BILI_PASS }}
    - name: CocoaPods Lint
      run: pod lib lint --verbose
    - name: Publish Jazzy Docs
      uses: Steven0351/publish-jazzy-docs@v1.1.1
      with:
        config: .jazzy.yaml
        personal_access_token: ${{ secrets.GITHUB_PAGES_TOKEN }}
